language: node_js

node_js:
  - '0.10'

env:
  matrix:
    - SAUCE_PLATFORM='Linux'      SAUCE_BROWSER='chrome'
    - SAUCE_PLATFORM='Linux'      SAUCE_BROWSER='firefox'
    # mouseMoveTo is unimplemented in the Safari Selenium driver
    # - SAUCE_PLATFORM='OS X 10.6'  SAUCE_BROWSER='safari' SAUCE_BROWSER_VERSION=5
    - SAUCE_PLATFORM='OS X 10.6'  SAUCE_BROWSER='chrome'
    # drag-and-drop testing seems to be broken on Sauce Mac-FF, not sure why
    # - SAUCE_PLATFORM='OS X 10.6'  SAUCE_BROWSER='firefox'
    - SAUCE_PLATFORM='Windows XP' SAUCE_BROWSER='internet explorer' SAUCE_BROWSER_VERSION=8
    - SAUCE_PLATFORM='Windows 7'  SAUCE_BROWSER='chrome'
    - SAUCE_PLATFORM='Windows 7'  SAUCE_BROWSER='firefox'
    - SAUCE_PLATFORM='Windows 7'  SAUCE_BROWSER='internet explorer' SAUCE_BROWSER_VERSION=9
    - SAUCE_PLATFORM='Windows 8'  SAUCE_BROWSER='internet explorer' SAUCE_BROWSER_VERSION=10

# Also make sure that nothing goes wrong on the server side when using node 0.8
matrix:
  include:
    - node_js: '0.8'
      env: SAUCE_PLATFORM='Linux' SAUCE_BROWSER='chrome'

before_script:
  - npm install forever
  - forever start test/webserver.js

script: npm run-script sauce-test

addons:
  sauce_connect:
    username: davidmikesimon
    access_key: "519e8897-9a6d-4f2c-81a1-10132cab95d0"
