language: node_js

node_js:
  - '0.10'

env:
  - SAUCE_PLATFORM='Linux'      SAUCE_BROWSER='chrome'
  - SAUCE_PLATFORM='Linux'      SAUCE_BROWSER='firefox'
  - SAUCE_PLATFORM='OS X 10.6'  SAUCE_BROWSER='safari'
  - SAUCE_PLATFORM='OS X 10.6'  SAUCE_BROWSER='chrome'
  - SAUCE_PLATFORM='OS X 10.6'  SAUCE_BROWSER='firefox'
  - SAUCE_PLATFORM='Windows XP' SAUCE_BROWSER='internet explorer'
  - SAUCE_PLATFORM='Windows 7'  SAUCE_BROWSER='chrome'
  - SAUCE_PLATFORM='Windows 7'  SAUCE_BROWSER='firefox'
  - SAUCE_PLATFORM='Windows 7'  SAUCE_BROWSER='internet explorer'
  - SAUCE_PLATFORM='Windows 8'  SAUCE_BROWSER='internet explorer'

# Also make sure that nothing goes wrong on the server side when using node 0.8
matrix:
  include:
    - node_js: '0.8'
    - env: SAUCE_PLATFORM='Linux' SAUCE_BROWSER='chrome'

before_script: node test/webserver.js

script: npm run-script sauce-test

addons:
  sauce_connect:
    username: davidmikesimon
    access_key: "519e8897-9a6d-4f2c-81a1-10132cab95d0"
